DROP DATABASE IF EXISTS proyecto;
CREATE DATABASE proyecto;
USE proyecto;
CREATE TABLE Jugador (
  ID INTEGER PRIMARY KEY NOT NULL,
  username TEXT NOT NULL,
  pass TEXT
)ENGINE = InnoDB;

CREATE TABLE Partida (
 ID INTEGER PRIMARY KEY NOT NULL,
 fecha DATE,
 hora TIME,
 duracion TIME,
 winner TEXT
)ENGINE = InnoDB;

CREATE TABLE Registro (
  ID INTEGER PRIMARY KEY NOT NULL,
  ID_J INTEGER NOT NULL,
  ID_P INTEGER NOT NULL,
  Puntos INTEGER NOT NULL,
  FOREIGN KEY (ID_J) REFERENCES Jugador(ID),
  FOREIGN KEY (ID_P) REFERENCES Partida(ID)
)ENGINE = InnoDB;

INSERT INTO Jugador VALUES(1,'Joan','aaaa');
INSERT INTO Jugador VALUES(2,'Maria','bbbb');
INSERT INTO Jugador VALUES(3,'Ana','cccc');
INSERT INTO Jugador VALUES(4,'Luis','dddd');
INSERT INTO Jugador VALUES(5,'Julia','eeee');

INSERT INTO Partida VALUES(1,'2024/03/01','10:45:00','00:15:20','Ana');
INSERT INTO Partida VALUES(2,'2024/02/23','11:45:00','00:16:20','Julia');
INSERT INTO Partida VALUES(3,'2024/02/10','12:45:00','00:17:20','Joan');

INSERT INTO Registro VALUES(1,1,1,10);
INSERT INTO Registro VALUES(2,2,1,20);
INSERT INTO Registro VALUES(3,3,1,20);
INSERT INTO Registro VALUES(4,4,1,30);
INSERT INTO Registro VALUES(5,1,2,10);
INSERT INTO Registro VALUES(6,2,2,10);
INSERT INTO Registro VALUES(7,3,2,30);
INSERT INTO Registro VALUES(8,5,2,5);
INSERT INTO Registro VALUES(9,1,3,10);
INSERT INTO Registro VALUES(10,2,3,10);
INSERT INTO Registro VALUES(11,3,3,5);
